name: turfit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+34

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  blobs: ^2.0.0
  bloc: ^9.0.0
  cached_network_image: null
  confetti: ^0.8.0
  equatable: ^2.0.7
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  geocoding: ^3.0.0
  geoflutterfire_plus: ^0.0.29
  geolocator: ^12.0.0
  get_it: ^7.7.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  linear_progress_bar: ^1.1.3
  lottie: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sizer: ^3.0.5
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/lottie/
