// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXOcHJpHJhaXOsE-6qdyrt2UeXNE7ZYaU',
    appId: '1:760266971868:android:e1343508a4bbe81fed7219',
    messagingSenderId: '760266971868',
    projectId: 'mealai-f58b5',
    storageBucket: 'mealai-f58b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDA-sAvK9lMg_vS2MuxV1E_-GL3FOkTt8',
    appId: '1:760266971868:ios:c77c2ffe6cf6b560ed7219',
    messagingSenderId: '760266971868',
    projectId: 'mealai-f58b5',
    storageBucket: 'mealai-f58b5.firebasestorage.app',
    androidClientId:
        '760266971868-g5p2me45nc29md4tghblkt25p3op5irt.apps.googleusercontent.com',
    iosClientId:
        '760266971868-fa0n62psp9vdnqvkugjshta6srh6hihv.apps.googleusercontent.com',
    iosBundleId: 'com.nomai.app',
  );
}
